spring:
  application:
    name: catalog-service
  # profiles:
  #    active:
  #    - dev
server:
  port: 8088
eureka:
  client:
    registerWithEureka: True
    fetchRegistry: true
    serviceUrl:
      defailtZone: http://localhost:8070/eureka
    instance:
      preferIpAddress: true
